quotes_project/app_quote/urls.py
from django.urls import path

from . import views


app_name = 'app_quotes'

urlpatterns = [
    path('', views.index, name='index'),
    path('init/', views.initialize_database, name='init'),
    path('my-quotes/', views.my_quotes, name='my-quotes'),
    path('author/<int:pk>', views.author, name='author'),
    path('add-quotes/', views.QuoteView.as_view(), name='add-quotes'),
    path('add-author/', views.AuthorView.as_view(), name='add-author'),
    path('remove/<int:pk>', views.remove_quote, name='remove'),
    path('edit-quote/<int:pk>/', views.QuoteUpdateView.as_view(), name='edit-quote'),
    path('tag/<str:tag>', views.tags, name='tag')
]

quotes_project/app_user/urls.py
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from .views import RegisterView
from .forms import LoginForm
from . import views

app_name = 'app_user'

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='signup'),
    path('signin/', LoginView.as_view(
        template_name='app_user/signin.html',
        form_class=LoginForm,
        redirect_authenticated_user=True), name='signin'),
    path('logout/', LogoutView.as_view(template_name='app_user/logout.html'), name='logout'),

    # ==================================================================================================

    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='app_user/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='app_user/password_reset_confirm.html',
                                          success_url='/user/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='app_user/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes_project/quotes_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('app_quote.urls', namespace='app_quotes')),
    path('user/', include('app_user.urls', namespace='app_user')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes_project/app_quote/models.py
from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    fullname = models.CharField(max_length=100)
    born_date = models.DateField()
    born_location = models.CharField(max_length=150)
    description = models.TextField()

    def __str__(self):
        return self.fullname

    class Meta:
        ordering = ['fullname']


class Tag(models.Model):
    name = models.CharField(max_length=40, unique=True, null=False)

    def __str__(self):
        return self.name


class Quote(models.Model):
    tags = models.ManyToManyField(Tag, related_name='quotes')
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    quote = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

quotes_project/app_quote/forms.py
from django.forms import CharField, DateField, ModelChoiceField, TextInput, ModelForm, DateInput, Select, Textarea

from .models import Quote, Author, Tag


class AuthorForm(ModelForm):
    fullname = CharField(
        max_length=100,
        required=True,
        widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Fullname'}))

    born_date = DateField(
        required=True,
        widget=DateInput(attrs={'class': 'form-control', 'placeholder': 'Born Date', 'type': 'date'}))

    born_location = CharField(
        max_length=150,
        required=True,
        widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Born Location'}))

    description = CharField(
        required=True,
        widget=Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'})
    )

    class Meta:
        model = Author
        fields = ('fullname', 'born_date', 'born_location', 'description')


class QuoteForm(ModelForm):
    quote = CharField(
        required=True,
        widget=Textarea(attrs={'class': 'form-control', 'placeholder': 'Quote'}))

    author = ModelChoiceField(
        queryset=Author.objects.all(),
        required=True,
        widget=Select(attrs={'class': 'form-select'}))

    tags = CharField(
        max_length=150,
        required=True,
        widget=TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Tags - live, sport, love, friendship'}),
        help_text='Enter tags separated by commas.'
    )

    class Meta:
        model = Quote
        fields = ('quote', 'author', 'tags')

    def save(self, commit=True):
        quote = super().save(commit=False)
        if commit:
            quote.save()
        tags_str = self.cleaned_data['tags']
        tags_list = [tag.strip() for tag in tags_str.split(',') if tag.strip()]
        for tag_name in tags_list:
            tag_obj, created = Tag.objects.get_or_create(name=tag_name)
            quote.tags.add(tag_obj)
        return quote


class QuoteEditForm(ModelForm):
    tags = CharField(
        required=True,
        widget=TextInput(attrs={'class': 'form-control'}),
        help_text='Enter tags separated by commas.',
        label=False
    )

    class Meta:
        model = Quote
        fields = ['quote', 'author']
        widgets = {
            'quote': Textarea(attrs={'class': 'form-control'}),
            'author': Select(attrs={'class': 'form-select'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['tags'].initial = ', '.join([tag.name for tag in self.instance.tags.all()])

    def save(self, commit=True):
        quote = super().save(commit=False)
        if commit:
            quote.save()
        tags_str = self.cleaned_data['tags']
        tags_list = [tag.strip() for tag in tags_str.split(',') if tag.strip()]
        quote.tags.clear()
        for tag_name in tags_list:
            tag_obj, created = Tag.objects.get_or_create(name=tag_name)
            quote.tags.add(tag_obj)
        return quote

quotes_project/app_quote/views.py
import json
from pathlib import Path

from django.core.paginator import Paginator
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import CreateView, UpdateView
from django.urls import reverse_lazy
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Count

import dateparser

from .models import Quote, Author, Tag
from .forms import QuoteForm, AuthorForm, QuoteEditForm
from .scrap import QuotesSpider, run_spider


@login_required
def initialize_database(request):

    if Path(QuotesSpider.file_path_author).is_file() or Path(QuotesSpider.file_path_quotes_tags).is_file():
        return redirect('app_quotes:index')

    run_spider()

    with open(QuotesSpider.file_path_author, 'r', encoding='utf-8') as file:
        result = json.load(file)

        for item in result:
            author_result = Author(
                fullname=item['fullname'],
                born_date=dateparser.parse(item['born_date']).date(),
                born_location=item['born_location'],
                description=item['description'],
            )
            author_result.save()

    with open(QuotesSpider.file_path_quotes_tags, 'r', encoding='utf-8') as file:
        result = json.load(file)

        for item in result:
            try:
                author_result = Author.objects.get(fullname=item['author'])
                user_result = User.objects.first()
            except Author.DoesNotExist:
                author_result = None
            if author_result:
                quote = Quote(
                    quote=item['quote'],
                    author=author_result,
                    created_by_id=user_result.id,
                )
                quote.save()
                for tag_name in item['tags']:
                    tag_obj, _ = Tag.objects.get_or_create(name=tag_name)
                    quote.tags.add(tag_obj)
    return redirect('app_quotes:index')


def index(request):
    result_quotes = Quote.objects.all().order_by('id')
    paginator = Paginator(result_quotes, settings.PAGE_SIZE)
    tags_result = Tag.objects.annotate(quote_count=Count('quotes')).order_by('-quote_count')[:10]
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "page_obj": page_obj,
        'title': 'Quotes | Home',
        "top_tags": tags_result
    }
    return render(request, 'app_quote/index.html', context)


def tags(request, tag):
    result_quotes = Quote.objects.filter(tags__name__in=[tag]).order_by('id').all()
    tags_result = Tag.objects.annotate(quote_count=Count('quotes')).order_by('-quote_count')[:10]
    paginator = Paginator(result_quotes, settings.PAGE_SIZE)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
        'title': 'Search result for ' + tag,
        "search_request": tag,
        "top_tags": tags_result
    }
    return render(request, 'app_quote/search.html', context)


def author(request, pk):
    result_author = Author.objects.get(pk=pk)
    context = {
        "result_author": result_author,
        'title': 'About ' + result_author.fullname
    }
    return render(request, 'app_quote/author.html', context)


@login_required
def my_quotes(request):
    result_quotes = Quote.objects.filter(created_by_id=request.user.id).order_by('id')
    paginator = Paginator(result_quotes, settings.PAGE_SIZE)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, 'app_quote/my-quotes.html', context={'page_obj': page_obj})


@login_required
def remove_quote(request, pk):
    quote = get_object_or_404(Quote, pk=pk)
    if quote.created_by != request.user:
        raise PermissionDenied('You are not allowed to delete this quote.')
    quote.delete()
    # invalidate_all_cache()
    return redirect('app_quotes:my-quotes')


class QuoteView(LoginRequiredMixin, CreateView):
    model = Quote
    form_class = QuoteForm
    template_name = 'app_quote/add-quote.html'
    success_url = reverse_lazy('app_quotes:my-quotes')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class AuthorView(LoginRequiredMixin, CreateView):
    model = Author
    form_class = AuthorForm
    template_name = 'app_quote/add-author.html'
    success_url = reverse_lazy('app_quotes:my-quotes')


class QuoteUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Quote
    form_class = QuoteEditForm
    template_name = 'app_quote/edit-quote.html'
    success_url = reverse_lazy('app_quotes:my-quotes')

    def test_func(self):
        quote = self.get_object()
        return quote.created_by == self.request.user

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            raise PermissionDenied('You are not allowed to edit this object.')
        else:
            return super().handle_no_permission()

#
# def invalidate_all_cache():
#     cache.clear()

quotes_project/app_quote/templates/app_quote/add-author.html
{% extends 'app_quote/base.html' %}

{% block content %}

    <h3>Add Author</h3>
    <form method="post" class="mb-3">
        {% csrf_token %}
        {% if form.errors and form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <div class="mb-3">
            {{ form.fullname }}
        </div>
        <div class="mb-3">
            {{ form.born_date }}
        </div>
        <div class="mb-3">
            {{ form.born_location }}
        </div>
        <div class="mb-3">
            {{ form.description }}
        </div>
        <div class="d-flex mt-3">
            <div class="col-10">
                <button type="submit" class="btn btn-outline-secondary w-100">Add Author</button>
            </div>
            <div class="flex-grow-1 ms-2 col-2">
                {% if previous_url %}
                    <a href="{{ previous_url }}" class="btn btn-secondary w-100">Cancel</a>
                {% else %}
                    <a href="{% url 'app_quotes:index' %}" class="btn btn-secondary w-100">Homepage</a>
                {% endif %}
            </div>
        </div>
    </form>

{% endblock %}

quotes_project/app_quote/templates/app_quote/add-quote.html
{% extends 'app_quote/base.html' %}

{% block content %}
    <h3>Add Quote</h3>
    <form class="mb-3" method="post">
        {% csrf_token %}
        <div class="col-12">
            <div class="input-group w-100">
                {{ form.author }}
            </div>
        </div>
        <div class="col-12 mt-3">
            <div class="input-group w-100">
                {{ form.tags }}
            </div>
            {% if form.tags.help_text %}
                <small class="form-text text-muted">{{ form.tags.help_text }}</small>
            {% endif %}
        </div>
        <div class="col-12 mt-3">
            <div class="input-group w-100">
                {{ form.quote }}
            </div>

        </div>
        {% if form.errors %}
            <div class="alert alert-danger mt-3">
                <ul class="mb-0">
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        <div class="d-flex mt-3">
            <div class="col-10">
                <button type="submit" class="btn btn-outline-secondary w-100">Add Quote</button>
            </div>
            <div class="flex-grow-1 ms-2 col-2">
                {% if previous_url %}
                    <a href="{{ previous_url }}" class="btn btn-secondary w-100">Cancel</a>
                {% else %}
                    <a href="{% url 'app_quotes:index' %}" class="btn btn-secondary w-100">Homepage</a>
                {% endif %}
            </div>
        </div>
    </form>
{% endblock %}

quotes_project/app_quote/templates/app_quote/author.html
{% extends 'app_quote/base.html' %}

{% block content %}

<h1>{{ result_author.fullname }}</h1>
<div class="">

    <div class="card-body">
        <p class="card-text author-text">Born: {{ result_author.born_date }} {{ result_author.born_location }}</p>
        <div>
            <p class="fs-6 fw-semibold mb-1 ">Description</p>
            <p class="fs-6 description-text">{{ result_author.description }}</p>
        </div>
        <div class="flex-grow-1 col-2">
                {% if previous_url %}
                    <a href="{{ previous_url }}" class="btn btn-secondary w-100">Back</a>
                {% else %}
                    <a href="{% url 'app_quotes:index' %}" class="btn btn-secondary w-100">Homepage</a>
                {% endif %}
            </div>
    </div>
</div>
{% endblock %}

quotes_project/app_quote/templates/app_quote/index.html
{% extends 'app_quote/base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Quotes to Scrape</h1>
    {% endif %}
    {% if page_obj %}
        <div class="row">
            <div class="row mt-5 col-9 ">
                {% for quote in page_obj %}
                    <div class="card mb-4 bg-color-card">
                        <div class="card-body">
                            <p class="card-text">{{ quote.quote }}</p>
                            <hr>
                            <div>
                                <span class="fs-6">By</span>
                                <span class="fs-6 fw-semibold">{{ quote.author }}</span>
                                <a href="{% url 'app_quotes:author' quote.author.id %}"
                                   class="link-offset-2 link-underline link-underline-opacity-0 link-opacity-50-hover">about</a>
                            </div>
                            <div class="row mt-3">
                                <div class="col tags-c">
                                    <span>Tags: </span>
                                </div>
                                <div class="col-11">
                                    {% for tag in quote.tags.all %}
                                        <a type="button" class="btn btn-outline-secondary btn-sm p-0 px-1"
                                           href="{% url 'app_quotes:tag' tag.name %}">{{ tag.name }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class="d-grid gap-2 col-6 mx-auto pagination text-center">
                <span class="step-links">
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-secondary" href="?page=1">&laquo; first</a>
                <a class="btn btn-outline-secondary" href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
                    <span class="current ms-2">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                    {% if page_obj.has_next %}
                        <a class="btn btn-outline-secondary ms-2" href="?page={{ page_obj.next_page_number }}">next</a>
                        <a class="btn btn-outline-secondary"
                           href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
                </div>
            </div>
            <div class="mt-5 col-3">
                <div class="end-text-block">
                    <h2 class="mb-3 top-ten-tags">Top Ten Tags</h2>
                    {% for tag in top_tags %}
                        <div class="nav justify-content-end mb-1">
                            <div>
                                <a type="button" class="btn btn-outline-secondary btn-sm p-0 px-2 top-tag-item" style="font-size:
                                        {% if forloop.counter0 == 0 %} 28px {% endif %}
                                        {% if forloop.counter0 == 1 %} 26px {% endif %}
                                        {% if forloop.counter0 == 2 %} 24px {% endif %}
                                        {% if forloop.counter0 == 3 %} 22px {% endif %}
                                        {% if forloop.counter0 == 4 %} 20px {% endif %}
                                        {% if forloop.counter0 == 5 %} 18px {% endif %}
                                        {% if forloop.counter0 == 6 %} 16px {% endif %}
                                        {% if forloop.counter0 == 7 %} 14px {% endif %}
                                        {% if forloop.counter0 == 8 %} 12px {% endif %}
                                        {% if forloop.counter0 == 9 %} 10px {% endif %}"
                                   href="{% url 'app_quotes:tag' tag.name %}">{{ tag.name }}</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
        {% if user.is_authenticated %}
            <div class="position-absolute top-50 start-50 translate-middle">
                <a class="btn btn-outline-secondary" href="{% url 'app_quotes:init' %}">Initialization of basic data</a>
            </div>
        {% else %}
            <div class="d-grid gap-2 mx-auto  position-absolute top-50 start-50 translate-middle">
                <h4 class="">To initialize basic data, please login/register</h4>
                <a class="btn btn-outline-secondary " href="{% url 'app_user:signin' %}">Signin</a>
                <a class="btn btn-outline-secondary " href="{% url 'app_user:signup' %}">Create an account</a>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

quotes_project/app_quote/templates/app_quote/my-quotes.html
{% extends 'app_quote/base.html' %}

{% block content %}
    <div class="row g-2">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <a class="btn btn-outline-secondary me-md-2" type="button" href="{% url 'app_quotes:add-author' %}">Add
                Author</a>
            <a class="btn btn-outline-secondary" type="button" href="{% url 'app_quotes:add-quotes' %}">Add Quote</a>
        </div>
        <h3>My Quotes</h3>
        <table class="table table-dark">
            <thead>
            <tr>
                <th scope="col" style="width: 3%;">#</th>
                <th scope="col" style="width: 15%;">Author</th>
                <th scope="col" style="width: 58%;">Quote</th>
                <th scope="col" style="width: 10%;">Tags</th>
                <th scope="col" style="width: 7%; text-align: right;">Manage</th>
            </tr>
            </thead>
            {% for quote in page_obj %}
                <tbody>
                <tr>
                    <th scope="row">{{ quote.id }}</th>
                    <td>{{ quote.author }}</td>
                    <td>{{ quote.quote }}</td>
                    <td>{% for tag in quote.tags.all %} {{ tag.name }} {% endfor %}</td>
                    <td class="text-align-right">
                        <form method="POST" action="#">
                            {% csrf_token %}
                            <a type="submit" class="btn btn-outline-secondary btn-sm mb-2 min-width-55"
                               href="{% url 'app_quotes:edit-quote' quote.id %}">edit</a>
                        </form>
                        <form method="POST" action="{% url 'app_quotes:remove' quote.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-danger btn-sm min-width-55 del-btn"
                                    onclick="return confirmDelete()">Delete
                            </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="d-grid gap-2 col-6 mx-auto pagination text-center">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-secondary" href="?page=1">&laquo; first</a>
            <a class="btn btn-outline-secondary" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current ms-2">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a class="btn btn-outline-secondary ms-2" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="btn btn-outline-secondary" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>
    <script>
        function confirmDelete() {
            return confirm("Are you sure you want to delete this quote?");
        }
    </script>
{% endblock %}

quotes_project/app_quote/templates/app_quote/panel.html
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-5">
    <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">

            <ul class="navbar-nav me-auto mb-2 mb-lg-0 w-100">

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'app_quotes:index' %}">Home</a>
                </li>
                <li class="nav-item ms-auto"></li>
                {% if user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_quotes:my-quotes' %}">My Quotes</a>
                    </li>
                    <li class="nav-item">
                        <form method="POST" action="{% url 'app_user:logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="nav-link btn btn-link">Logout</button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_user:signin' %}">Signin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_user:signup' %}">Signup</a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>

quotes_project/app_quote/templates/app_quote/search.html
{% extends 'app_quote/base.html' %}


{% block content %}
    {% if user.is_authenticated %}
        <h1>Search result for "{{ search_request }}"</h1>
    {% endif %}
    {% if page_obj %}
        <div class="row">
            <div class="row mt-5 col-9 ">
                {% for quote in page_obj %}
                    <div class="card mb-4 bg-color-card">
                        <div class="card-body">
                            <p class="card-text">{{ quote.quote }}</p>
                            <hr>
                            <div>
                                <span class="fs-6">By</span>
                                <span class="fs-6 fw-semibold">{{ quote.author }}</span>
                                <a href="{% url 'app_quotes:author' quote.author.id %}"
                                   class="link-offset-2 link-underline link-underline-opacity-0 link-opacity-50-hover">about</a>
                            </div>
                            <div class="row mt-3">
                                <div class="col tags-c">
                                    <span>Tags: </span>
                                </div>
                                <div class="col-11">
                                    {% for tag in quote.tags.all %}
                                        <a type="button" class="btn btn-outline-secondary btn-sm p-0 px-1"
                                           href="{% url 'app_quotes:tag' tag.name %}">{{ tag.name }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class="d-grid gap-2 col-6 mx-auto pagination text-center">
                <span class="step-links">
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-secondary" href="?page=1">&laquo; first</a>
                <a class="btn btn-outline-secondary" href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
                    <span class="current ms-2">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                    {% if page_obj.has_next %}
                        <a class="btn btn-outline-secondary ms-2" href="?page={{ page_obj.next_page_number }}">next</a>
                        <a class="btn btn-outline-secondary"
                           href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
                </div>
            </div>
            <div class="mt-5 col-3">
                <div class="end-text-block">
                    <h2 class="mb-3 top-ten-tags">Top Ten Tags</h2>
                    {% for tag in top_tags %}
                        <div class="nav justify-content-end mb-1">
                            <div>
                                <a type="button" class="btn btn-outline-secondary btn-sm p-0 px-2 top-tag-item" style="font-size:
                                        {% if forloop.counter0 == 0 %} 28px {% endif %}
                                        {% if forloop.counter0 == 1 %} 26px {% endif %}
                                        {% if forloop.counter0 == 2 %} 24px {% endif %}
                                        {% if forloop.counter0 == 3 %} 22px {% endif %}
                                        {% if forloop.counter0 == 4 %} 20px {% endif %}
                                        {% if forloop.counter0 == 5 %} 18px {% endif %}
                                        {% if forloop.counter0 == 6 %} 16px {% endif %}
                                        {% if forloop.counter0 == 7 %} 14px {% endif %}
                                        {% if forloop.counter0 == 8 %} 12px {% endif %}
                                        {% if forloop.counter0 == 9 %} 10px {% endif %}"
                                   href="{% url 'app_quotes:tag' tag.name %}">{{ tag.name }}</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
        {% if user.is_authenticated %}
            <div class="position-absolute top-50 start-50 translate-middle">
                <a class="btn btn-primary" href="{% url 'app_quotes:init' %}">Initialization of basic data</a>
            </div>
        {% else %}
            <div class="d-grid gap-2 mx-auto  position-absolute top-50 start-50 translate-middle">
                <h4 class="">To initialize basic data, please login/register</h4>
                <a class="btn btn-outline-primary" href="{% url 'app_user:signin' %}">Signin</a>
                <a class="btn btn-outline-primary" href="{% url 'app_user:signup' %}">Create an account</a>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}