quotes_project/app_user/urls.py
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from .views import RegisterView
from .forms import LoginForm
from . import views

app_name = 'app_user'

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='signup'),
    path('signin/', LoginView.as_view(
        template_name='app_user/signin.html',
        form_class=LoginForm,
        redirect_authenticated_user=True), name='signin'),
    path('logout/', LogoutView.as_view(template_name='app_user/logout.html'), name='logout'),

    # ==================================================================================================

    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='app_user/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='app_user/password_reset_confirm.html',
                                          success_url='/user/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='app_user/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes_project/quotes_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('app_quote.urls', namespace='app_quotes')),
    path('user/', include('app_user.urls', namespace='app_user')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes_project/app_user/models.py
from django.db import models

# Create your models here.

quotes_project/app_user/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, EmailInput, TextInput, EmailField, PasswordInput


class RegisterForm(UserCreationForm):
    username = CharField(max_length=50, min_length=3, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    email = EmailField(max_length=40, required=True, widget=EmailInput(attrs={'class': 'form-control'}))
    password1 = CharField(required=True, widget=PasswordInput(attrs={'class': 'form-control'}))
    password2 = CharField(required=True, widget=PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = CharField(max_length=50, min_length=3, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    password = CharField(required=True, widget=PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'password')

quotes_project/app_user/views.py
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.contrib import messages

from .forms import RegisterForm


class RegisterView(View):
    template_name = 'app_user/signup.html'
    form_class = RegisterForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('quotes:index')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f'Account created for {username}')
            return redirect('app_quotes:index')
        return render(request, self.template_name, {'form': form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'app_user/password_reset_html.html'
    email_template_name = 'app_user/password_reset_email.html'
    html_email_template_name = 'app_user/password_reset_email.html'
    success_url = reverse_lazy('app_user:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'app_user/password_reset_subject.txt'

quotes_project/app_user/templates/app_user/logout.html
{% extends 'app_quote/base.html' %}

quotes_project/app_user/templates/app_user/password_reset_complete.html
{% extends "app_quote/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

quotes_project/app_user/templates/app_user/password_reset_confirm.html
{% extends "app_quote/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

quotes_project/app_user/templates/app_user/password_reset_done.html
{% extends "app_quote/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

quotes_project/app_user/templates/app_user/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'app_user:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'app_user:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

quotes_project/app_user/templates/app_user/password_reset_html.html
{% extends "app_quote/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

quotes_project/app_user/templates/app_user/signin.html
{% extends 'app_quote/base.html' %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-5">
                <div class="card-body p-5 mt-5">
                    <h2 class="text-center mb-5">Signin</h2>
                    {% if messages %}
                        <div class="messages">
                            {% for message in messages %}
                                <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                                {{ message }}
                            {% endfor %}
                            </span>
                        </div>
                    {% endif %}

                    {% if form.errors and form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            {{ form.username }}
                            <label for="fullname">Username</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.password }}
                            <label for="password">Password</label>
                        </div>
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-outline-secondary ">Signin</button>
                        </div>
                        <div class="text-center text-muted mt-5 mb-0">Don't have an account?
                            <a href="{% url 'app_user:signup' %}">
                                <u>Sign up here</u>
                            </a>
                        </div>
                        <div class="small text-center">
                            <a href="{% url "app_user:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

quotes_project/app_user/templates/app_user/signup.html
{% extends 'app_quote/base.html' %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-6">
                <div class="card-body p-5 mt-5">
                    <h2 class="text-center mb-5">Create an account</h2>
                    {% if messages %}
                        <div class="messages">
                            {% for message in messages %}
                                <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                                {{ message }}
                            {% endfor %}
                            </span>
                        </div>
                    {% endif %}

                    {% if form.errors and form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            {{ form.username }}
                            <label for="fullname">
                                Fullname
                            </label>
                            <span class="text-danger">{{ form.errors.username }}</span>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.email }}
                            <label for="email">
                                Email address
                            </label>
                            <span class="text-danger">{{ form.errors.email }}</span>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.password1 }}
                            <label for="password">
                                Password
                            </label>
                            <span class="text-danger">{{ form.errors.password1 }}</span>
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.password2 }}
                            <label for="confirm_password">
                                Confirm password
                            </label>
                            <span class="text-danger">{{ form.errors.password2 }}</span>
                        </div>
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-outline-secondary ">Register</button>
                            <button type="reset" class="btn btn-secondary">Reset</button>
                        </div>

                        <div class="text-center text-muted mt-5 mb-0">Have already an account?
                            <a href="{% url 'app_user:signin' %}">
                                <u>Login here</u>
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}